version: '3.2'
services:
  aws-console:
    image: aws-console
    build: .
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: .
        target: /project
      - ./root:/root
